spring.application.name=fixlog
spring.config.import=optional:file:.env.properties
server.servlet.context-path=/fixlog

# Google OAuth2 Client
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# DataSource
spring.datasource.url=jdbc:mariadb://${DB_URL}/fixlog
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# CORS
cors.allowed-origins=http://localhost:5173

# OAuth2
oauth2.success-redirect-url=http://localhost:5173/login/callback

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiry=1800000
jwt.refresh-token-expiry=1209600000
